### ISSUE TITLE
Use Agloe for map management.

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [AltitudeMapdev/Issues#103]
Plastix recently open-sourced (now closed sourced again) a plugin called [Agloe](https://github.com/Plastix/Agloe), which is almost the same plugin as Elevation with Dropbox uploading, permissions to view the world, and etc.

I think we should switch to Agloe and use Spigot to run the server, or has Altitude been cancelled?

**Comment by skipperguy12** [comment]
Altitude is not cancelled, and Agloe is based off of Elevation. We are currently revamping Elevation as the old one wasn't quite as good as we'd like it to be.

**Comment by molenzwiebel** [comment]
Agloe is based off Elevation code and was open sourced with our permission. We are currently working on revamping our world management and backup system, with the intention of releasing begin 2015.
