### ISSUE TITLE
Website suggestions

### ISSUE THREAD

**Issue by Matic0B** [AltitudeMapdev/Issues#12]
- [x] Improve footer with tabs or pills
- [ ] Add a 404.html page **[INVALID]**
- [x] The group on the left in getting_started doesnt seem to be working
- [x] Move the navbar so it starts a little later more to the right and move the Log In nav to pull-right 
- [x] Make the navbar go cross screen like on OCN not stop when it reaches the end (I saw the rounded edges meaning it stops)
- [x] On the shop.html page move the username box lower down with **[ITS FINE]**
- [ ] Post the IP somewhere on the website **[not invalid, working on it. -olly]**

**Comment by Matic0B** [comment]
Make the 404.html page prettier and a way to return back to the main site. I just saw it. Sry bout the invalid thing

**Comment by AustinLMayes** [comment]
Checkboxes!

**Comment by itsmiiolly** [comment]
How the fuck did you do that...? XD

EDIT: Oh it's normal markdown. I didn't even know github was able to do that lol.

**Comment by itsmiiolly** [comment]
Looks like everything on here was completed.
