### ISSUE TITLE
Give users a way to get full worldedit perms without having to pay any money

### ISSUE THREAD

**Issue by KalikaTheCat** [AltitudeMapdev/Issues#14]
Worldedit perms are a basic right on mapdev servers.

I can see where you are coming from with the lag issues, but having some sort of rank to gain full perms after showing they are trustworthy would be good.

**Comment by ghost** [comment]
We'd also have to be careful to ensure the server wont crash. I do think there should be some kind of max limit, even for trustworthy. Right now it's set at 30k, so maybe set it at 80k or so for trustworthy? I'm not sure how bad that'd lag everything, but meh.

**Comment by Matic0B** [comment]
I would say trusted would have extended limit to WE and Voxel. Possibly trusted would be 72 hours of play time and atleast 5 maps created and /download -ed.

**Comment by Timothee38** [comment]
I suggest to allow the (normal) users to have something such as a 15 radius brush or so maximum for voxel sniper!

**Comment by BlockDrop74** [comment]
I think pretty much everyone should have Worldedit, but as ieat had said, a limit. The testers could come up with good amount, that is big, but won't lag the server, and settle upon that limit. People who are just starting, would get a little less than that, trusted would get the limit talked about above. And the staff/owners of Altitude would get unlimited. I believe no payment should be involved in having such a needed tool.

**Comment by molenzwiebel** [comment]
Note that AsyncWorldEdit is installed, as well as two (2) server instances running. This partially to reduce WorldEdit load. The limit can be a bit higher, but certainly not unlimited.

**Comment by Electroid** [comment]
@molenzwiebel We can talk about this. We should design a different version of world edit. If there is no queues for commands then it doesn't use async. But as more and more commands come in, it dynamically uses async. If a command is above half a million blocks, it will auto-save and backup everything prior. I believe strongly all users should not have a hard limit. But a dynamic one.

**Comment by itsmiiolly** [comment]
Everyone now has (mostly) full access to WorldEdit.
