### ISSUE TITLE
Error with the spawn protections

### ISSUE THREAD

**Issue by Timothee38** [AltitudeMapdev/Issues#16]
Ok, so I generated my world and started to build in it, but I found a bug. As you can see on the video, I can place blocks, but cant destroy them afterwards. I think this is due to a spawn protection radius or so.
https://www.youtube.com/watch?v=GG5AE_dQPgA&feature=youtu.be

Thanks for fixing anything.

**Comment by itsmiiolly** [comment]
Changing the spawn-protection values to 0 should fix it. @skipperguy12

**Comment by Timothee38** [comment]
ok!
