### ISSUE TITLE
Unable to craft

### ISSUE THREAD

**Issue by Matic0B** [AltitudeMapdev/Issues#17]
I tried to color some armor in the crafting table, but every time I put an item into the 3x3 square the item was put back into my inventory, making me unable to craft.

I also tried in the 2x2 square on survival and the error was still there.

I disconnected and joined back but that did not fix it.

**Comment by itsmiiolly** [comment]
Unable to produce.

**Comment by Matic0B** [comment]
nvm olly restarted the server - all fine
