### ISSUE TITLE
404 image not on website

### ISSUE THREAD

**Issue by BrummyNinetySeven** [AltitudeMapdev/Issues#2]
I think that ya'll should put the picture of the carrot on your own assets folder of using someone else's (http://www.blocksandgold.com/media/catalog/product/cache/3/image/9df78eab33525d08d6e5fb8d27136e95/c/a/carrot.png)

**Comment by AustinLMayes** [comment]
No.

**Comment by molenzwiebel** [comment]
Yes

**Comment by itsmiiolly** [comment]
lol

**Comment by itsmiiolly** [comment]
Fixed :)
