### ISSUE TITLE
[Urgent] Putting Items in Inventory

### ISSUE THREAD

**Issue by BlockDrop74** [AltitudeMapdev/Issues#21]
**Caused by MyMaps book**

Whenever I would put items into my inventory, they disappear. This doesn't happen with the main nine slots, but does with the extra 27 slots, as well as armor.

**Comment by itsmiiolly** [comment]
Are you lagging by any chance? Can anyone reproduce?

**Comment by BlockDrop74** [comment]
@ItsMiiOlly I'm not lagging at all from what I see. The items never re-appear, they are just taken out of my inventory, never to be found again.

**Comment by itsmiiolly** [comment]
Does it happen as soon as you put the items in? Is anyone else getting the same issue?

**Comment by BlockDrop74** [comment]
@ItsMiiOlly Yes, right when I put them in my inventory, they disappear.

**Comment by itsmiiolly** [comment]
Is anyone else getting the same issue?

**Comment by hdt80** [comment]
I'm not but I'm op

**Comment by BlockDrop74** [comment]
@ItsMiiOlly I was able to get a video of what's going on exactly. Also, it seems the bottom 9 slots of the 27 are fine, but not the top 18. Here's a link: https://www.youtube.com/watch?v=6w5u6Yo7AbQ

**Comment by itsmiiolly** [comment]
Alright, thanks.

**Comment by itsmiiolly** [comment]
Unable to reproduce.

**Comment by AustinLMayes** [comment]
@ItsMiiOlly You're opped

**Comment by molenzwiebel** [comment]
Can reproduce, even though I have OP.

**Comment by BlockDrop74** [comment]
@molenzwiebel I was able to place items in the 18 slots earlier, now it's back, it seems it happens sometimes, and not others.

**Comment by AustinLMayes** [comment]
Confirmed to only happen when elevation is loaded. Any ideas @molenzwiebel ?

**Comment by molenzwiebel** [comment]
After experimenting a bit on localhost, I have not been able to reproduce this problem on my own server (so I get it on Altitude, but not on localhost). I have tried:
- non elevation-enabled worlds
- elevation-enabled world, me being owner of world, OP
- elevation-enabled world, me being owner of world, not OP
- elevation-enabled world, someone else being owner of world, OP
- elevation-enabled world, someone else being owner of world, not OP

and I could not reproduce it. Maybe a combination of plugins that cause this problem?

EDIT: Can someone confirm this still exists? I cannot reproduce it on Altitude anymore.

**Comment by BlockDrop74** [comment]
@molenzwiebel It still happens for me

**Comment by itsmiiolly** [comment]
Confirmed & still exists.

**Comment by itsmiiolly** [comment]
I've done a bit of testing on my server a couple of weeks ago and concluded that the MyMaps book is causing this. Switching to using a list view of your maps should fix the problem.

**Comment by itsmiiolly** [comment]
We're pleased to announce that this has been fixed. Thanks @hdt80 !
