### ISSUE TITLE
Moving at all lags you back

### ISSUE THREAD

**Issue by Moo8x8** [AltitudeMapdev/Issues#25]
Very new to this, no idea what to put here, but yea -  Whenever you move around, you lag back into place - extremely annoying

**Comment by itsmiiolly** [comment]
Not sure what is causing the issue...

**Comment by Moo8x8** [comment]
I think it's only 1.7.5 that causes this, I tried 1.7.2 and it was fine...

**Comment by itsmiiolly** [comment]
That's very odd. Let me have a go.
