### ISSUE TITLE
[Suggestion] Name Alerts

### ISSUE THREAD

**Issue by BlockDrop74** [AltitudeMapdev/Issues#26]
On one of the MapDevs I would work on, if a players full username was said in chat, they would get a sound played as an alert sent to them. I suggest the same thing be implemented here on Altitude. Or maybe, if the player receives a pm, they would get an alert.

**Comment by hdt80** [comment]
I'll do it if no one was objections

**Comment by BlockDrop74** [comment]
@hdt80 I just thought about it, and this could be spammed. Maybe also make it so the sound can only be played once every minute?

**Comment by hdt80** [comment]
or just use /ignore or soemthing like that

**Comment by Dinner1111** [comment]
I gave olly the plugin from PepDev
