### ISSUE TITLE
No platform spawns when I generate a world

### ISSUE THREAD

**Issue by Timothee38** [AltitudeMapdev/Issues#27]
Not sure if it's meant to be like that, but I would add a platform maybe (like 1 to 5 blocks of bedrock) when somebody spawns on the world, not everyone will have the thing to do /up 1.
But basically, I did /create Timothee then /map Timothee and spawned in the air, kind of glitching, with not blocks under my character.

**Comment by AustinLMayes** [comment]
Worlds are created with a block of bedrock at spawn.

**Comment by hdt80** [comment]
not for me.

**Comment by Timothee38** [comment]
not for me either then.

**Comment by hdt80** [comment]
To clarify I nor tim don't have bedrock at 0,0. Maybe this bedrock is at the world spawn?

**Comment by molenzwiebel** [comment]
This is not a bug, it is just not implemented yet (not after the transition to Elevation 2.0 that is). Will add it in a bit.

**Comment by Timothee38** [comment]
ok.
