### ISSUE TITLE
Teleporting to Worlds

### ISSUE THREAD

**Issue by BlockDrop74** [AltitudeMapdev/Issues#28]
I currently have a problem with teleporting to worlds. Whenever I would type /map BlockDrop74, I would instead get tped to Avaleer's world, Ava1. So, I currently cannot access my own world. It even is the same for using the book to teleport.

**Comment by itsmiiolly** [comment]
This has been a known bug for a while and we're not sure what is causing it. I'll have to mess around with unload times and see if that fixes it.

**Comment by hdt80** [comment]
Its appears that a restart fixes it.

**Comment by itsmiiolly** [comment]
Dupe of #11
