### ISSUE TITLE
[Sug] Custom mobs

### ISSUE THREAD

**Issue by ryanwarsaw** [AltitudeMapdev/Issues#29]
Being able to use a plugin to create custom entities. Edit things such as its armor, color (villagers), and nametag as well as enable the ability to put potion effects and change other NBT data of the mob. :)

**Comment by itsmiiolly** [comment]
Pretty sure all of this can be done with the plugin 'NBTEdit' we have on the server. Look in the help menu for commands. :)

**Comment by AustinLMayes** [comment]
This repository is not for feature requests regardless.
