### ISSUE TITLE
Temporarily remove Summit because we use BukkitPermissions now

### ISSUE THREAD

**Issue by itsmiiolly** [AltitudeMapdev/Issues#31]
We're temporarily using BukkitPermissions now because Summit isn't complete. We can either:
- Remove Summit or disable it
- Remove everyone from the groups on Summit so I can properly apply the prefixes etc

**Comment by AustinLMayes** [comment]
Remove Summit, is broken

**Comment by itsmiiolly** [comment]
@NathanTheBook does this affect anything like the downloads?

**Comment by AustinLMayes** [comment]
Elevatin handles downloads

**Comment by itsmiiolly** [comment]
@NathanTheBook yay
