### ISSUE TITLE
Using /give without specifying an amount gives a "ghost item"

### ISSUE THREAD

**Issue by JsKingBoo** [AltitudeMapdev/Issues#34]
I'm guessing it's because the item's stack count is 0 or negative

To reproduce:
1. Fill your hotbar with random crap (not doing this step deletes the ghost item on click)
2. Type "/give you anything" with "anything" not being any of the random crap you filled your hotbar with, and "anything" must be stackable (like a stick)
3. Empty one slot of your hotbar
4. Shift click the ghost item. You should see a cloned item on your hotbar
5. Shift click the ghost item again. The original ghost item should stack with the cloned item
6. Move the ghost item back to its original location. The cloned item should be deleted
7. Empty your inventory by shift clicking the red X of the creative menu. The ghost item should stay
8. Try picking up the ghost item with your mouse. It should stick to its original location
9. Pick up the ghost item again. You should be moving it now.
10. Move the ghost item over the red X of the creative menu and delete it.
11. Create a stack of random junk and place it on the ghost item's original location. The ghost item should return.
12. Create a stack of the ghost item (default is middle click)
13. Right click and drag it in every spot in your inventory.
14. Release right click. The top two rows should be deleted randomly
15. Type "/kill" in chat and pick up the items you dropped. They are normal items now.

Note: There are more properties of this annoying "ghost item", but I think I've listed enough

**Comment by AustinLMayes** [comment]
There has been a wired bug with the top two rows of an inventory getting stuck. The problem is caused by Elevation (can reproduce locally) and we are working on that. As for /give, it's command book.

**Comment by itsmiiolly** [comment]
We'll continue discussion on #21 .
