### ISSUE TITLE
Dying in a locked world allows items to drop on the ground

### ISSUE THREAD

**Issue by Narwhale** [AltitudeMapdev/Issues#36]
(1) /kill
(2) items fall on the ground

![](http://i.imgur.com/YTJH1bM.png)

**Comment by AustinLMayes** [comment]
Would you rather have them drop and pick them up or they dissapear and you potentially loose a kit of items that took an hour to make?

**Comment by Narwhale** [comment]
This is a locked world though, you can't even pick them back up with out unlocking it.

**Comment by AustinLMayes** [comment]
oooo
I'll fix this then

**Comment by AustinLMayes** [comment]
A fix is being sent to your address now
