### ISSUE TITLE
People can still TP to you even when the world is set to private / when you're not added to it

### ISSUE THREAD

**Issue by itsmiiolly** [AltitudeMapdev/Issues#37]
Frac set his world to PRIVATE but I can still TP to him (however, I can't go to his world be doing /map xxfracxx).

I'm not opped and my permission group was set to default.

**Comment by AustinLMayes** [comment]
I believe @Plastix fixed this on his branch.

**Comment by molenzwiebel** [comment]
Custom TP commands are still not added, although they are done for quite some time now. Someone should put them in

**Comment by itsmiiolly** [comment]
@molenzwiebel Skipper managed to merge this into Elevation and it works.

**Comment by molenzwiebel** [comment]
Cool, good to see you guys managing stuff without me :p

**Comment by itsmiiolly** [comment]
@molenzwiebel Altitude has turned into chaos!!! Everything's on fire and shit pls come bak!!!

**Comment by Plastix** [comment]
Oh god please use correct spelling...

**Comment by itsmiiolly** [comment]
@Plastix Haha :P
