### ISSUE TITLE
MOTD gets reset after restarting the server

### ISSUE THREAD

**Issue by Narwhale** [AltitudeMapdev/Issues#39]
Olly just fixed the motd today but after a restart it reset to the default motd. It seems like restarting the server causes a lot of problems for some reason...

![](http://i.imgur.com/YYtVQZ8.png)

**Comment by itsmiiolly** [comment]
I haven't fixed the MOTD yet. I'll work on it in a bit :p

**Comment by AustinLMayes** [comment]
I blame the waffles

**Comment by itsmiiolly** [comment]
MOTD doesn't reset.
