### ISSUE TITLE
Slow page loading

### ISSUE THREAD

**Issue by BrummyNinetySeven** [AltitudeMapdev/Issues#4]
I'm not sure if it's just me but http://mapdev.it/revisions/web takes an awfully long time to load and switch though the tabs

**Comment by molenzwiebel** [comment]
It is currently using a github api, but we (I) are thinking of switching it to something a lot faster.

**Comment by AustinLMayes** [comment]
@molenzwiebel Care to share?

**Comment by itsmiiolly** [comment]
This _might_ be a Github issue, but there is no fix for it.
