### ISSUE TITLE
Setting yourself as AFK with /afk gives you 2 messages

### ISSUE THREAD

**Issue by Narwhale** [AltitudeMapdev/Issues#41]
![](http://i.imgur.com/vFY9PYg.png)

**Comment by itsmiiolly** [comment]
This is intended.

**Comment by AustinLMayes** [comment]
Wait what? BHow is that intentional? That just looks down right unprofesionsal. /cc @ItsMiiOlly

**Comment by itsmiiolly** [comment]
This is how the commandbook author made it. We don't need to change it.
