### ISSUE TITLE
/c syntax message is messed up?

### ISSUE THREAD

**Issue by Narwhale** [AltitudeMapdev/Issues#42]
It should say /c [message], not just /c

![](http://i.imgur.com/Naia7be.png)

**Comment by hdt80** [comment]
yeah, I've been busy with other things, I'll work on buildsquad tommorow.

**Comment by molenzwiebel** [comment]
Only /c is possible as well though, it switches your chat channel. (/g for global)

**Comment by hdt80** [comment]
Olly wanted me to remove that.

**Comment by hdt80** [comment]
Fixed.

**Comment by molenzwiebel** [comment]
Please use a commit with "fixes AltitudeMapdev/Issues#42" so it closes automagically (as well as shows the ones who have access the commit) when you fix it. Thanks :)
