### ISSUE TITLE
Creating a second world should name it "<username>_2"

### ISSUE THREAD

**Issue by itsmiiolly** [AltitudeMapdev/Issues#45]
Only donators will be able to name their own worlds, so when normal users create a second world, it should be named "<username>_2". 

Currently, when a second world is created, it will still name it "<username>".

**Comment by molenzwiebel** [comment]
This is actually really weird... The code does not check for donator, but instead for > 1 worlds allowed. Non-donators with 2+ worlds should be able to rename them. I guess Elevation doesn't check the arguments (and relies on the users intellect instead).

**Comment by itsmiiolly** [comment]
I can possibly get @skipperguy12 or @RainoBoy97 to fix this. :)

**Comment by molenzwiebel** [comment]
Just make a new issue in the Elevation repo I guess

**Comment by itsmiiolly** [comment]
This was partly fixed by @hdt80 but it should reflect the amount of worlds you have (eg ItsMiiOlly_3, ItsMiiOlly_4 etc).

**Comment by hdt80** [comment]
I thought I fixed that in the latest commit.

**Comment by itsmiiolly** [comment]
This has been fixed.
