### ISSUE TITLE
[Urgent] Deletion bug

### ISSUE THREAD

**Issue by itsmiiolly** [AltitudeMapdev/Issues#46]
Let's say I have two worlds: ItsMiiOlly and ItsMiiOlly2. When I go into ItsMiiOlly2 and delete it, it will delete ItsMiiOlly and not the one I'm in.

This is a pretty major bug and should be fixed quickly.

**Comment by AustinLMayes** [comment]
You should post these possibly game-breaking issues in the Elevation repo.
