### ISSUE TITLE
Configuration reload command

### ISSUE THREAD

**Issue by itsmiiolly** [AltitudeMapdev/Issues#48]
Just a simple suggestion: `/elevation reload [world]` helpful for reloading the plugin config or a specified world's config.

**Comment by AustinLMayes** [comment]
1. This should be on the private repos's issues.
2. We can discuss further there

**Comment by itsmiiolly** [comment]
Why does it need to be there? What's wrong with posting it here?

**Comment by molenzwiebel** [comment]
This repo is mainly for issues that are relevant for _the users_ of Altitude. If the issue is for a specific plugin, and you have access to that repo, please make it in the private repo (for clarity).

**Comment by itsmiiolly** [comment]
rude
