### ISSUE TITLE
Wrong coloring in some pages

### ISSUE THREAD

**Issue by Matic0B** [AltitudeMapdev/Issues#50]
The word "NOTE" is colored red in the Teams tab when in all others its black.

Teams
http://gyazo.com/38a94159fd8e1a584b23f1038e11757a
Others:
http://gyazo.com/0ab528183b98fc088c8fe82de0c52fb8
http://gyazo.com/57bf6097dad8330f33826d0d2b26d13e

Same goes for the FAQ site. "NOTE" is colored red.
http://gyazo.com/939afc196a0e1a28b0b99b508dde5c5d
http://gyazo.com/b04e0202c1e688199f6da086c16b606c

**Comment by itsmiiolly** [comment]
Fixed, thanks.
