### ISSUE TITLE
Extreme lag while using "Your Worlds" book.

### ISSUE THREAD

**Issue by ryanwarsaw** [AltitudeMapdev/Issues#54]
When you type /mymaps -b you get a book containing all your worlds. 

When right clicking the book its about a 5 to 6 second delay before the book opens up.

This lag also allows players to pick up the "wool" and drag it around their inventory. This only lasts for 5 to 6 seconds before the lag stops and the player teleports. With or without wool in hand.

When teleporting to the world you are in, within the worlds book. There is virtually no lag. You can still drag the wool around the chest GUI however.

When teleporting to a world you own, sometimes you will get spammed the "Teleportation message".

This does not happen when you teleport to a INVITEE world.

![2014-08-09_19 17 53](https://cloud.githubusercontent.com/assets/6530909/3868005/74ca4b68-201b-11e4-8b38-98cd18318a18.png)

Suggested fix?

I assume some of the lag has to deal with the worlds having to load before the player can teleport. I am not sure about why it spams messages, or why that doesn't happen to a other persons world.

**Comment by Matic0B** [comment]
I think its your connection

**Comment by itsmiiolly** [comment]
It _may_ be due to lag.

**Comment by itsmiiolly** [comment]
I can reproduce this bug. When I teleport to the world "EnderDragon" it spams the message and seems to TP to matic's world too. Idk how often this happens. 

```
[11:37:37] [Client thread/INFO]: [CHAT] Teleported you to matic0basle
[11:37:38] [Client thread/INFO]: [CHAT] Teleported you to EnderDragon
[11:37:38] [Client thread/INFO]: [CHAT] Teleported you to EnderDragon
```
