### ISSUE TITLE
mymaps command GUI is broken.

### ISSUE THREAD

**Issue by ryanwarsaw** [AltitudeMapdev/Issues#55]
The entire GUI is broken, the wools and data show up correctly, its just when you click the wools they do  not do anything. You can take them out, like any normal chest. Clicking them just picks them up.

**Comment by Pingy** [comment]
This happened to me once thinking I was lagging.

**Comment by itsmiiolly** [comment]
The map menu works for me. Are you sure it isn't just lag?

**Comment by ryanwarsaw** [comment]
No, I can confirm that the /mymaps GUI is broken. Not because of lag.

**Comment by Matic0B** [comment]
Its probably lag. Im not experiencing this

**Comment by ryanwarsaw** [comment]
![capture](https://cloud.githubusercontent.com/assets/6530909/3869537/3ff4d9d2-2096-11e4-85f1-104e0de7f6a2.PNG)

I am not lagging. I assure you.

**Comment by itsmiiolly** [comment]
idk then

**Comment by ryanwarsaw** [comment]
I think its fair to say this is a code related issue, and not a server issue. /mymaps -b works perfectly fine.

I believe its just a code related problem.

**Comment by Dinner1111** [comment]
It cannot be a code related problem if users cannot reproduce under the same conditions. Can you provide any more details?

**Comment by ryanwarsaw** [comment]
@Dinner1111 I believe they are referring to /mymaps -b and I am referring to /mymaps.

**Comment by itsmiiolly** [comment]
`/mymaps` will default to a list soon anyway.

**Comment by itsmiiolly** [comment]
Switching to #59
