### ISSUE TITLE
Automatically add build team members to each other's worlds.

### ISSUE THREAD

**Issue by AnthonyTag** [AltitudeMapdev/Issues#63]
Seeming they are a build team they should trust each other to build together. But I can see how this could possibly be abused.

**Comment by EyQu** [comment]
+1

**Comment by ryanwarsaw** [comment]
-1 Not a good idea. Thats why the server has staff. For disputes like this.

**Comment by Matic0B** [comment]
/state team
It would give viewing permissions to team members for that world

Small suggestion

**Comment by itsmiiolly** [comment]
@rywarsaw what?

I love this idea. I'll make sure the devs get round to adding this.

**Comment by ryanwarsaw** [comment]
@matic0basle I like your idea!

**Comment by ryanwarsaw** [comment]
The nostalgia lol

**Comment by AnthonyTag** [comment]
@ryanwse lmao just came back to close my old open issues (sry for the ping people)

**Comment by AustinLMayes** [comment]
OMG HI GUIS

**Comment by CoWinkKeyDinkInc** [comment]
Altitude Map Dev comeback confirmed??!?!

**Comment by itsmiiolly** [comment]
maybe on another server ;)
