### ISSUE TITLE
Afk doesn't detect movement on y axis

### ISSUE THREAD

**Issue by Pingy** [AltitudeMapdev/Issues#65]
If you do /afk and go up and down, it doesn't say "You are now not marked as afk"

**Comment by gcflames5** [comment]
@Pingy I don't think this really matters, any other action that the player does will trigger it, odds are they won't just be moving up and down and doing nothing, I'll look into this though, thanks.

**Comment by itsmiiolly** [comment]
This is a bug with commandbook and is something extremely minor that we won't bother fixing it. :P
