### ISSUE TITLE
Infractions not colo(u)red 

### ISSUE THREAD

**Issue by SuperArmor** [AltitudeMapdev/Issues#7]
./l <name>
Picture: http://i.imgur.com/mYhVj5s.png
The § symbol or the & does not change the colo(u)r thus resulting in the picture.

Olly made me post this .-.

**Comment by molenzwiebel** [comment]
Error with the locale on the operating system not knowing the character §. I can't fix this, electroid needs to

**Comment by AustinLMayes** [comment]
I have no idea what plugin that is. Someone needs to update to latest Moderator and remove permit.

**Comment by AustinLMayes** [comment]
Fixed when new Moderator is deployed
