### ISSUE TITLE
AFK glitched in the player list

### ISSUE THREAD

**Issue by Matic0B** [AltitudeMapdev/Issues#74]
I went AFK for a second but when I came back it never said im no longer AFK so my name in the tab list is staying red

![](http://i.imgur.com/sGj8svx.png)

![](http://i.imgur.com/R4YCcV1.png)

**Comment by itsmiiolly** [comment]
I'm not getting this error.

**Comment by Matic0B** [comment]
@ItsMiiOlly It was a one time thing for me as well but I still reported it in case it repeats

**Comment by AustinLMayes** [comment]
It's a commandbook bug.
