### ISSUE TITLE
New command - /memberlist

### ISSUE THREAD

**Issue by Matic0B** [AltitudeMapdev/Issues#77]
Displays the list of people that have permission to view the world and that have build permission.
The list could also say if the person is a member or a builder

**Comment by itsmiiolly** [comment]
![image](http://i.imgur.com/nX3Ks1O.png)

**Comment by itsmiiolly** [comment]
^Member list and new (possible) colours

**Comment by itsmiiolly** [comment]
New changes pushed to the new Elevation build.
