### ISSUE TITLE
Revision link - 404

### ISSUE THREAD

**Issue by Matic0B** [AltitudeMapdev/Issues#83]
Clicking on the link in the revisions will lead you to a github 404 page.

I wouldn't say its a bug because the code is private so it should not show it but don't link the revision? Just display the number but dont link to github.

![](http://i.gyazo.com/1272e8eca7d0db85eff94d9dbbc56a46.png)

**Comment by AustinLMayes** [comment]
The repository is private.

**Comment by Matic0B** [comment]
@NathanTheBook And that why instead of a link it should just be text

**Comment by skipperguy12** [comment]
@matic0basle It's still helpful to people who do have access to it. However, I can see why it would create some confusion. I'm sure we could just check for admin log in.
