### ISSUE TITLE
Messed up shop packages

### ISSUE THREAD

**Issue by Matic0B** [AltitudeMapdev/Issues#89]
![](http://i.gyazo.com/8ab1d72102ae268c3047045e2502c761.png)

The website donor package says your world cap gets increased to 3 worlds but the shop it self says 5 worlds.

![](http://i.gyazo.com/741e6ea2043e83a1957f64cfcb9794bb.png)

**Comment by ryanwarsaw** [comment]
eZ

**Comment by gcflames5** [comment]
@NathanTheBook ufix
