### ISSUE TITLE
No command to confirm

### ISSUE THREAD

**Issue by Matic0B** [AltitudeMapdev/Issues#92]
![](http://i.gyazo.com/5886fbb62e372fba4151b8f69fb4e08f.png)

I did /confirm right after i did /delete (less than 15 seconds).

Tried deleting multiple times (under 15 seconds) and still nothing.

**Comment by molenzwiebel** [comment]
Try /elevation:confirm. CommandBook might override it because someone changed its settings

**Comment by Matic0B** [comment]
@molenzwiebel That worked.

**Comment by itsmiiolly** [comment]
We had a commandbook version that removed this but someone replaced it with the old version
