### ISSUE TITLE
Log in typo

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [AltitudeMapdev/Issues#98]
Remember me check box says "Remeber Me".

**Comment by 058c37a272bed3464d47f0b01038a16a** [comment]
@NathanTheBook

**Comment by CoWinkKeyDinkInc** [comment]
Why did you close it?  Is this server coming back?

**Comment by 058c37a272bed3464d47f0b01038a16a** [comment]
@AustinLMayes just likes closing year old issues.
